on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to echo on each push
    steps:
    - name: Echo (on each push)
      id: echo
      uses: bioimagesuiteweb/bisweb/actions/push@devel
