# test.yml
name: 'Hosted YML'
description: 'Regression test'
outputs:
    result: # id of output
      description: 'The abbreviated results file'
    logfile: # id of output
      description: 'The complete log file'
runs:
  using: 'docker'
  image: './Dockerfile'
