on: 
  schedule:
    - cron: '33 5 * * *'


jobs:
  unix_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-18.04]
    name: bisweb-test
    steps:
    - name: Global Prereqs
      run: |
        sudo npm install -g gulp mocha rimraf
        sudo python3 -m pip install --upgrade pip setuptools
        sudo python3 -m pip install numpy nibabel
    - name: Clone
      run: |
        mkdir -p /tmp/bisweb/src
        cd /tmp/bisweb
        git clone https://github.com/bioimagesuiteweb/bisweb src
        cd src
        git checkout devel
        git pull
        cp npm-shrinkwrap-orig.json npm-shrinkwrap.json
    - name: Clone Plugin
      run: |
        cd /tmp/bisweb
        mkdir -p /tmp/bisweb/gpl
        git clone https://github.com/bioimagesuiteweb/gplcppcode gpl
        cd gpl
        git pull
    - name : Python Prereqs
      run: |
        cd /tmp/bisweb/src
        python3 -m pip install --user -r biswebpython/config/requirements.txt
    - name : JS Prereqs
      run: |
        cd /tmp/bisweb/src
        npm install -d
        node config/createbuild.js
    - name : Build
      run: |
        cd /tmp/bisweb/src/build
        echo "Copying files"
        chmod +x /tmp/bisweb/src/build/*.sh
        chmod +x /tmp/bisweb/src/compiletools/*.sh
        echo "-------------------------------------------------"
        echo "Beginning build"
        echo "-------------------------------------------------"
        bash /tmp/bisweb/src/compiletools/fullbuild.sh
        cd /tmp/bisweb/src
    - name : Test
      run : bash /tmp/bisweb/src/actions/hosted/dockeractiontest.sh /tmp 1 1000
      id: run    
    - name: Results
      run: echo "${{ steps.run.outputs.result}}"
    - name: Store Results
      uses: actions/upload-artifact@v1
      with:
        name: logs
        path: /tmp/bisweb/src/build/output/logs
    - name: Store Libraries
      uses: actions/upload-artifact@v1
      with:
        name: libraries
        path: /tmp/bisweb/src/build/output/libraries
